# Generated by Django 5.0.2 on 2024-02-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_remove_link_user_link_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
